- name: setup catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: Create a dedicated application user
    ansible.builtin.user:
        name: roboshop
        comment: "robohsop system user"
        shell: /sbin/nologin
        system: true
        home: /app
  
  - name: Delete directory
    ansible.builtin.file:
        path: /app
        state: absent
  
  - name: create directory
    ansible.builtin.file:
        path: /app
        state: directory
  
  - name: Delete catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent
  
  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  
  