- name: Creating Ec2 Instance and Route53
  hosts: local
  connection: local
  vars:
    AMI_ID: ami-09c813fb71547fc4f
    Instnace_ID: i-017c9856718c1df33
    Security_Group: sg-07e88823124a6dddf
    Domain_Name: "cloudskills.fun"
    instances: 
    - mongodb
  tasks: 
  - name: create ec2 Instance
    amazon.aws.ec2_instance:
       name: "{{ item }}"    #mongodb
       instance_type: t2.micro
       image_id: "{{ AMI_ID }}"
       security_group: "{{ Security_Group }}"
       tags:
         Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: Print EC2 ec2_output
    ansible.builtin.debug:
         msg: "{{ ec2_output.results }}"

#pip3.9 install botocore boto3
# ansible wrote in pyhton , if ansible wants to contact aws , aws is expecting python libraries