- name: setup mongodb server
  hosts: mongodb
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
  