- name: setup mongodb server
  hosts: mongodb
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
    
    - name: Installing MongoDB server
      ansible.builtin.package:
           name: mongodb-org
           state: present

    - name: Enable Service 
      ansible.builtin.service:
           name: mongod
           state: started
           enabled: yes

    - name: Allow remote connections
      ansible.builtin.replace:
           path: /etc/mongod.conf
           regexp: '127.0.0.1'
           replace: '0.0.0.0'

    - name: Restart Service
      ansible.builtin.service:
           name: mongod
           state: started
           enabled: yes