- name: Setup User server
  hosts: user
  become: yes
  tasks:

  - name: Disabling Nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Disabling default redis
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Installing Nodejs 
    ansible.builtin.package:
        name: nodejs 
        state: present

  - name: Add application user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      shell: /sbin/nologin
      home: /app
  
  #safe to remove app directory , because 2nd time if we run it will download freshly, no error if doesnt exist
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory 
    ansible.builtin.file:
       state: directory
       path: /app

  - name: Delete user file
    ansible.builtin.file:
       path: /tmp/user.zip
       state: absent
  
  - name: Download user
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
       dest: /tmp/user.zip

  - name: Extract user.zip into /app
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes 

  - name: Install packages based on package.json.
    community.general.npm:
       path: /app
    
  - name: copying the file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service   
  
  - name: copying the file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb
    ansible.builtin.package:
       name: mongodb-mongosh
       state: present

  - name: connnect to mongodb user
    ansible.builtin.command: mongosh mongodb.cloudskills.fun --quiet --eval "db.getMongo().getDBNames().indexOf('user')"
    register: user_output

  - name: Load Products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.cloudskills.fun </app/db/master-data.js
    when: user_output.stdout | int < 0

  - name: start and enable catagloue
    ansible.builtin.service:
       name: user
       enabled: yes
       state: started
  
  - name: daemon reload enable and start 
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true



  